image: docker:latest

services:
 - docker:18.09.7-dind

variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2

stages:
 - build
 - deploy

before_script:
 - docker info


build-centos6:
 stage: build
 except:
  refs:
   - master
 script:
  - docker build -t buildpack-centos6 $CI_PROJECT_DIR/centos6
  - docker tag buildpack-centos6 udienz/buildpack:centos6
  - docker login -u="$DOCKERUSER" -p="$DOCKERPASS"
  - docker push udienz/buildpack:centos6
  - docker login git.wow.net.id:5050 -u mahyuddin -p"$GITLAB_PRIVATE_TOKEN"
  - docker tag buildpack-centos6 git.wow.net.id:5050/mahyuddin/docker-buildpack:centos6
  - docker push git.wow.net.id:5050/mahyuddin/docker-buildpack:centos6

build-centos7:
 stage: build
 except:
  refs:
   - master
 script:
  - docker build -t buildpack-centos7 $CI_PROJECT_DIR/centos7
  - docker tag buildpack-centos7 udienz/buildpack:centos7
  - docker login -u="$DOCKERUSER" -p="$DOCKERPASS"
  - docker push udienz/buildpack:centos7
  - docker login git.wow.net.id:5050 -u mahyuddin -p"$GITLAB_PRIVATE_TOKEN"
  - docker tag buildpack-centos7 git.wow.net.id:5050/mahyuddin/docker-buildpack:centos7
  - docker push git.wow.net.id:5050/mahyuddin/docker-buildpack:centos7

build-precise:
 stage: build
 except:
  refs:
   - master
 script:
  - docker build -t buildpack-precise $CI_PROJECT_DIR/precise
  - docker tag buildpack-precise udienz/buildpack:precise
  - docker login -u="$DOCKERUSER" -p="$DOCKERPASS"
  - docker push udienz/buildpack:precise
  - docker login git.wow.net.id:5050 -u mahyuddin -p"$GITLAB_PRIVATE_TOKEN"
  - docker tag buildpack-precise git.wow.net.id:5050/mahyuddin/docker-buildpack:precise
  - docker push git.wow.net.id:5050/mahyuddin/docker-buildpack:precise

build-trusty:
 stage: build
 except:
  refs:
   - master
 script:
  - docker build -t buildpack-trusty $CI_PROJECT_DIR/trusty
  - docker tag buildpack-trusty udienz/buildpack:trusty
  - docker login -u="$DOCKERUSER" -p="$DOCKERPASS"
  - docker push udienz/buildpack:trusty
  - docker login git.wow.net.id:5050 -u mahyuddin -p"$GITLAB_PRIVATE_TOKEN"
  - docker tag buildpack-trusty git.wow.net.id:5050/mahyuddin/docker-buildpack:trusty
  - docker push git.wow.net.id:5050/mahyuddin/docker-buildpack:trusty

build-xenial:
 stage: build
 except:
  refs:
   - master
 script:
  - docker build -t buildpack-xenial $CI_PROJECT_DIR/xenial
  - docker tag buildpack-xenial udienz/buildpack:xenial
  - docker login -u="$DOCKERUSER" -p="$DOCKERPASS"
  - docker push udienz/buildpack:xenial
  - docker login git.wow.net.id:5050 -u mahyuddin -p"$GITLAB_PRIVATE_TOKEN"
  - docker tag buildpack-xenial git.wow.net.id:5050/mahyuddin/docker-buildpack:xenial
  - docker push git.wow.net.id:5050/mahyuddin/docker-buildpack:xenial

build-bionic:
 stage: build
 except:
  refs:
   - master
 script:
  - docker build -t buildpack-bionic $CI_PROJECT_DIR/bionic
  - docker tag buildpack-bionic udienz/buildpack:bionic
  - docker login -u="$DOCKERUSER" -p="$DOCKERPASS"
  - docker push udienz/buildpack:bionic
  - docker login git.wow.net.id:5050 -u mahyuddin -p"$GITLAB_PRIVATE_TOKEN"
  - docker tag buildpack-bionic git.wow.net.id:5050/mahyuddin/docker-buildpack:bionic
  - docker push git.wow.net.id:5050/mahyuddin/docker-buildpack:bionic

build-focal:
 stage: build
 except:
  refs:
   - master
 script:
  - docker build -t buildpack-focal $CI_PROJECT_DIR/focal
  - docker tag buildpack-focal udienz/buildpack:focal
  - docker login -u="$DOCKERUSER" -p="$DOCKERPASS"
  - docker push udienz/buildpack:focal
  - docker login git.wow.net.id:5050 -u mahyuddin -p"$GITLAB_PRIVATE_TOKEN"
  - docker tag buildpack-focal git.wow.net.id:5050/mahyuddin/docker-buildpack:focal
  - docker push git.wow.net.id:5050/mahyuddin/docker-buildpack:focal

build-jessie:
 stage: build
 except:
  refs:
   - master
 script:
  - docker build -t buildpack-jessie $CI_PROJECT_DIR/jessie
  - docker tag buildpack-jessie udienz/buildpack:jessie
  - docker login -u="$DOCKERUSER" -p="$DOCKERPASS"
  - docker push udienz/buildpack:jessie
  - docker login git.wow.net.id:5050 -u mahyuddin -p"$GITLAB_PRIVATE_TOKEN"
  - docker tag buildpack-jessie git.wow.net.id:5050/mahyuddin/docker-buildpack:jessie
  - docker push git.wow.net.id:5050/mahyuddin/docker-buildpack:jessie

build-stretch:
 stage: build
 except:
  refs:
   - master
 script:
  - docker build -t buildpack-stretch $CI_PROJECT_DIR/stretch
  - docker tag buildpack-stretch udienz/buildpack:stretch
  - docker login -u="$DOCKERUSER" -p="$DOCKERPASS"
  - docker push udienz/buildpack:stretch
  - docker login git.wow.net.id:5050 -u mahyuddin -p"$GITLAB_PRIVATE_TOKEN"
  - docker tag buildpack-stretch git.wow.net.id:5050/mahyuddin/docker-buildpack:stretch
  - docker push git.wow.net.id:5050/mahyuddin/docker-buildpack:stretch

build-buster:
 stage: build
 except:
  refs:
   - master
 script:
  - docker build -t buildpack-buster $CI_PROJECT_DIR/buster
  - docker tag buildpack-buster udienz/buildpack:buster
  - docker login -u="$DOCKERUSER" -p="$DOCKERPASS"
  - docker push udienz/buildpack:buster
  - docker login git.wow.net.id:5050 -u mahyuddin -p"$GITLAB_PRIVATE_TOKEN"
  - docker tag buildpack-buster git.wow.net.id:5050/mahyuddin/docker-buildpack:buster
  - docker push git.wow.net.id:5050/mahyuddin/docker-buildpack:buster

build-alpine-edge:
 stage: build
 except:
  refs:
   - master
 script:
  - docker build -t buildpack-alpine-edge $CI_PROJECT_DIR/alpine-edge
  - docker tag buildpack-alpine-edge udienz/buildpack:alpine-edge
  - docker login -u="$DOCKERUSER" -p="$DOCKERPASS"
  - docker push udienz/buildpack:alpine-edge
  - docker login git.wow.net.id:5050 -u mahyuddin -p"$GITLAB_PRIVATE_TOKEN"
  - docker tag buildpack-alpine-edge git.wow.net.id:5050/mahyuddin/docker-buildpack:alpine-edge
  - docker push git.wow.net.id:5050/mahyuddin/docker-buildpack:alpine-edge

build-alpine-latest:
 stage: build
 except:
  refs:
   - master
 script:
  - docker build -t buildpack-alpine-latest $CI_PROJECT_DIR/alpine-latest
  - docker tag buildpack-alpine-latest udienz/buildpack:alpine-latest
  - docker login -u="$DOCKERUSER" -p="$DOCKERPASS"
  - docker push udienz/buildpack:alpine-latest
  - docker login git.wow.net.id:5050 -u mahyuddin -p"$GITLAB_PRIVATE_TOKEN"
  - docker tag buildpack-alpine-latest git.wow.net.id:5050/mahyuddin/docker-buildpack:alpine-latest
  - docker push git.wow.net.id:5050/mahyuddin/docker-buildpack:alpine-latest

openmerge:
    image: udienz/gitlab-merge-resource
    before_script: []
    stage: deploy
    except:
        refs:
            - master
    script:
        - HOST=${CI_PROJECT_URL} CI_PROJECT_ID=${CI_PROJECT_ID} CI_COMMIT_REF_NAME=${CI_COMMIT_REF_NAME} GITLAB_USER_ID=${GITLAB_USER_ID} PRIVATE_TOKEN=${GITLAB_PRIVATE_TOKEN} $CI_PROJECT_DIR/utils/merge.sh
    when: on_success

build-latest:
 stage: build
 except:
  refs:
   - master
 script:
  - docker build -t buildpack-latest $CI_PROJECT_DIR/focal
  - docker tag buildpack-latest udienz/buildpack:latest
  - docker login -u="$DOCKERUSER" -p="$DOCKERPASS"
  - docker push udienz/buildpack:alpine-latest
  - docker login git.wow.net.id:5050 -u mahyuddin -p"$GITLAB_PRIVATE_TOKEN"
  - docker tag buildpack-latest git.wow.net.id:5050/mahyuddin/docker-buildpack:latest
  - docker push git.wow.net.id:5050/mahyuddin/docker-buildpack:latest
