image: docker:latest

services:
 - docker:dind

stages:
 - build
 - deploy

before_script:
 - docker info


build-centos6:
 stage: build
 except:
  refs:
   - master
 script:
  - docker build -t buildpack-centos6 $CI_PROJECT_DIR/centos6
  - docker tag buildpack-centos6 udienz/buildpack:centos6
  - docker login -u="$DOCKERUSER" -p="$DOCKERPASS"
  - docker push udienz/buildpack:centos6

build-centos7:
 stage: build
 except:
  refs:
   - master
 script:
  - docker build -t buildpack-centos7 $CI_PROJECT_DIR/centos7
  - docker tag buildpack-centos7 udienz/buildpack:centos7
  - docker login -u="$DOCKERUSER" -p="$DOCKERPASS"
  - docker push udienz/buildpack:centos7

build-precise:
 stage: build
 except:
  refs:
   - master
 script:
  - docker build -t buildpack-precise $CI_PROJECT_DIR/precise
  - docker tag buildpack-precise udienz/buildpack:precise
  - docker login -u="$DOCKERUSER" -p="$DOCKERPASS"
  - docker push udienz/buildpack:precise

build-trusty:
 stage: build
 except:
  refs:
   - master
 script:
  - docker build -t buildpack-trusty $CI_PROJECT_DIR/trusty
  - docker tag buildpack-trusty udienz/buildpack:trusty
  - docker login -u="$DOCKERUSER" -p="$DOCKERPASS"
  - docker push udienz/buildpack:trusty

build-xenial:
 stage: build
 except:
  refs:
   - master
 script:
  - docker build -t buildpack-xenial $CI_PROJECT_DIR/xenial
  - docker tag buildpack-xenial udienz/buildpack:xenial
  - docker login -u="$DOCKERUSER" -p="$DOCKERPASS"
  - docker push udienz/buildpack:xenial

build-bionic:
 stage: build
 except:
  refs:
   - master
 script:
  - docker build -t buildpack-bionic $CI_PROJECT_DIR/bionic
  - docker tag buildpack-bionic udienz/buildpack:bionic
  - docker login -u="$DOCKERUSER" -p="$DOCKERPASS"
  - docker push udienz/buildpack:bionic

build-wheezy:
 stage: build
 except:
  refs:
   - master
 script:
  - docker build -t buildpack-wheezy $CI_PROJECT_DIR/wheezy
  - docker tag buildpack-wheezy udienz/buildpack:wheezy
  - docker login -u="$DOCKERUSER" -p="$DOCKERPASS"
  - docker push udienz/buildpack:wheezy

build-jessie:
 stage: build
 except:
  refs:
   - master
 script:
  - docker build -t buildpack-jessie $CI_PROJECT_DIR/jessie
  - docker tag buildpack-jessie udienz/buildpack:jessie
  - docker login -u="$DOCKERUSER" -p="$DOCKERPASS"
  - docker push udienz/buildpack:jessie

build-stretch:
 stage: build
 except:
  refs:
   - master
 script:
  - docker build -t buildpack-stretch $CI_PROJECT_DIR/stretch
  - docker tag buildpack-stretch udienz/buildpack:stretch
  - docker login -u="$DOCKERUSER" -p="$DOCKERPASS"
  - docker push udienz/buildpack:stretch

openmerge:
    image: udienz/gitlab-merge-resource
    before_script: []
    stage: deploy
    except:
        refs:
            - master
    script:
        - HOST=${CI_PROJECT_URL} CI_PROJECT_ID=${CI_PROJECT_ID} CI_COMMIT_REF_NAME=${CI_COMMIT_REF_NAME} GITLAB_USER_ID=${GITLAB_USER_ID} PRIVATE_TOKEN=${GITLAB_PRIVATE_TOKEN} $CI_PROJECT_DIR/utils/merge.sh
    when: on_success

build-latest:
 stage: build
 except:
  refs:
   - master
 script:
  - docker build -t buildpack-latest $CI_PROJECT_DIR/bionic
  - docker tag buildpack-latest udienz/buildpack:latest
  - docker login -u="$DOCKERUSER" -p="$DOCKERPASS"
  - docker push udienz/buildpack:latest
