name: Check focal Dockerfile
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "master", "development", "main" ]

jobs:
  build:
    runs-on: ["self-hosted"]
    steps: 
    - name: Checkout
      uses: actions/checkout@master
      
    - name: lint
      uses: luke142367/Docker-Lint-Action@v1.0.0
      with:
        target: focal/Dockerfile
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

