name: Check trusty Dockerfile
on: ["push", "pull_request"]

jobs:
  build:
    runs-on: ["self-hosted"]
    steps: 
    - name: Checkout
      uses: actions/checkout@master
      
    - name: lint
      uses: luke142367/Docker-Lint-Action@v1.0.0
      with:
        target: trusty/Dockerfile
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

